/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.phoneshop.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class Animation extends javax.swing.JFrame {
    private Timer tmrAnimation;

    /**
     * Creates new form Animation
     */
    public Animation() {
        initComponents();
        setLocationRelativeTo(null);
       setBackground(new Color(0,0,0,0f));
        
        tmrAnimation = new Timer(500,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pgLoading.setValue(pgLoading.getValue()+10);
            if(pgLoading.getValue()>=pgLoading.getMaximum()){
                tmrAnimation.stop();
                Animation.this.dispose();
                Log1 frmMain=new Log1();
               frmMain.setVisible(true);
            }
            }
        });
        tmrAnimation.start();
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOTmodify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        pgLoading = new javax.swing.JProgressBar();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel4.setText("Phone Shop Management System");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, 40));

        jXLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel3.setText("Thilakawardana");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 310, 50));

        jXLabel2.setText("Loading....");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, 30));

        pgLoading.setBackground(new java.awt.Color(230, 1, 0));
        pgLoading.setForeground(new java.awt.Color(238, 0, 0));
        pgLoading.setOpaque(true);
        jPanel1.add(pgLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 410, -1));

        jXLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/kau4to.png"))); // NOI18N
        jXLabel1.setOpaque(true);
        jPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private javax.swing.JProgressBar pgLoading;
    // End of variables declaration//GEN-END:variables
}
