/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.phoneshop.view;

//import static com.sun.deploy.uitoolkit.impl.fx.ui.FXUIFactory.showConfirmDialog;
import java.awt.TextComponent;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import lk.ijse.phoneshop.controller.ManageCustomerController;
import lk.ijse.phoneshop.core.dto.CustomerDTO;
import lk.ijse.phoneshop.validation.Validation;

/**
 *
 * @author HP
 */
public class CustomerManage extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerManage
     */
    public CustomerManage() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtNic = new org.jdesktop.swingx.JXTextField();
        txtName = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new org.jdesktop.swingx.JXTextArea();
        txtEmail = new org.jdesktop.swingx.JXTextField();
        txtTele = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        btnCreate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();

        jXPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel1.setText("Manage Customer");
        jXLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jXPanel2.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 470, 60));

        jXLabel2.setText("Name with Initials");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel2.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 180, 20));

        jXLabel3.setText("Address");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel2.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 20));

        jXLabel4.setText("e-mail Address");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel2.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, 20));

        jXLabel5.setText("TelePhone No.");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel2.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, 40));

        jXLabel6.setText("Customer NIC");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXPanel2.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 30));

        txtNic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        jXPanel2.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jXPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 360, 40));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(txtAddress);

        jXPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 360, 100));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jXPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 360, 40));

        txtTele.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleActionPerformed(evt);
            }
        });
        jXPanel2.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 180, 30));

        jXLabel8.setText("( xxx-xxxxxxx )");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel2.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 354, 120, 20));

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Create New.png"))); // NOI18N
        btnCreate.setText("Save New");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jXPanel2.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 180, 40));

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Search1.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jXPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, 40));

        btnRemove.setBackground(new java.awt.Color(204, 204, 204));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Remove.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jXPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 170, 40));

        btnChange.setBackground(new java.awt.Color(204, 204, 204));
        btnChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Change1.png"))); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jXPanel2.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 170, 40));

        btnView.setBackground(new java.awt.Color(204, 204, 204));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/View Reports.png"))); // NOI18N
        btnView.setText("Show All");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jXPanel2.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 170, 40));

        btnSearch1.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Clr.png"))); // NOI18N
        btnSearch1.setText("Refresh");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jXPanel2.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 40));

        jXLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jXPanel2.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        txtAddress.requestFocus();
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        String id = txtNic.getText();
        if (id.matches("[0-9]{9}[Vv]")) {
            String email = txtEmail.getText();
            if (email.matches("[a-z]+@[a-z]+\\.[a-z]+") || email.matches("")) {
                String tele = txtTele.getText();
                if (tele.matches("[0-9]{3}[-][0-9]{7}")) {
                    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure Added this Customer?");
                    if (confirm == 0) {
                        try {
                            CustomerDTO customer = new CustomerDTO(txtNic.getText(),
                                    txtName.getText(),
                                    txtAddress.getText(),
                                    txtEmail.getText(),
                                    txtTele.getText());

                            boolean result = ManageCustomerController.addCustomer(customer);

                            if (result) {
                                JOptionPane.showMessageDialog(this, "Customer has been successfully added.");
                                // loadAllItems();                
                            } else {
                                JOptionPane.showMessageDialog(this, "Customer hasn't been added due to some error");
                            }

                        } catch (Exception ex) {
                            Logger.getLogger(CustomerManage.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Tele Phone no. enter to Correct format");
                        txtTele.selectAll();
                        txtTele.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Fill Correct e-mail Address");
                    txtEmail.selectAll();
                    txtEmail.requestFocus();
                }

            } else {
                JOptionPane.showMessageDialog(this, "NIC no. enter to Correct Format");
                txtNic.selectAll();
                txtNic.requestFocus();

            }
        }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtTele.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleActionPerformed
        btnCreate.requestFocus();
    }//GEN-LAST:event_txtTeleActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Are You sure Deleted this customer?");
            if (confirm == 0) {
                CustomerDTO customer = new CustomerDTO(txtNic.getText(), txtName.getText(), txtAddress.getText(), txtEmail.getText(), txtTele.getText());
                boolean result = ManageCustomerController.deleteCustomer(customer);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Deleted...");
                    txtNic.setText("");
                    txtName.setText("");
                    txtAddress.setText("");
                    txtEmail.setText("");
                    txtTele.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Delete Failled");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed

        try {
            /*CustomerDTO customer=new CustomerDTO(txtNic.getText(),txtName.getText(),txtAddress.getText(),txtEmail.getText(),txtTele.getText());
            CustomerDTO result=ManageCustomerController.updateCustomer(customer);
            if(result)*/
            int confirm=JOptionPane.showConfirmDialog(this,"Are You sure Update this Values?");
            CustomerDTO customer = new CustomerDTO(txtNic.getText(), txtName.getText(), txtAddress.getText(), txtEmail.getText(), txtTele.getText());
            boolean isAdded = ManageCustomerController.updateCustomer(customer);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Successfully Update..");

            } else {
                JOptionPane.showMessageDialog(this, "Update Failled");
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        CustomerDTO customer = new CustomerDTO(txtNic.getText());
        try {

            CustomerDTO result = ManageCustomerController.searchCustomer(customer);
            if (result != null) {
                txtName.setText(result.getCusName());
                txtAddress.setText(result.getCusAddress());
                txtEmail.setText(result.getEmail());
                txtTele.setText(result.getTele());
            } else {
                JOptionPane.showMessageDialog(this, "No Such Customer");
            }

        } catch (Exception ex) {
            Logger.getLogger(CustomerManage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        ViewCustomer c1 = new ViewCustomer();
        c1.setVisible(true);
    }//GEN-LAST:event_btnViewMouseClicked

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        txtName.requestFocus();
    }//GEN-LAST:event_txtNicActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        txtNic.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtTele.setText("");
    }//GEN-LAST:event_btnSearch1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTextArea txtAddress;
    private org.jdesktop.swingx.JXTextField txtEmail;
    private org.jdesktop.swingx.JXTextField txtName;
    private org.jdesktop.swingx.JXTextField txtNic;
    private org.jdesktop.swingx.JXTextField txtTele;
    // End of variables declaration//GEN-END:variables

}
