/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.phoneshop.view;

import java.awt.Color;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author HP
 */
public class Home1 extends javax.swing.JFrame {

   private static String userId;

    /**
     * Creates new form Home1
     */
    public Home1() {
        initComponents();
        setDate();
        setTime();
    }

    public Home1(String userid) {
        this.userId=userid;
        
        initComponents();
        setDate();
        setTime();
        visibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        lblTime = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        lblDate = new org.jdesktop.swingx.JXLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        lblReturn = new org.jdesktop.swingx.JXLabel();
        lblCus = new org.jdesktop.swingx.JXLabel();
        lblItem = new org.jdesktop.swingx.JXLabel();
        lblSup = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXPanel5 = new org.jdesktop.swingx.JXPanel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        lblSupOrder = new org.jdesktop.swingx.JXLabel();
        lblCusOrder = new org.jdesktop.swingx.JXLabel();
        lblView = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        lblOrDetail = new org.jdesktop.swingx.JXLabel();
        lblEmployee = new org.jdesktop.swingx.JXLabel();
        lblUser = new org.jdesktop.swingx.JXLabel();
        pnlHme = new org.jdesktop.swingx.JXPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel2.setText("Thilakawardana Phone Shop");
        jXLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jXPanel3.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 678, 80));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Logout-64.png"))); // NOI18N
        jXLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel1MousePressed(evt);
            }
        });
        jXPanel3.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jXPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 201, 44));
        jXPanel3.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 110, 235, 167));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jXPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 216, 64));

        jXPanel2.add(jXPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1370, 230));

        jXPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReturn.setBackground(new java.awt.Color(204, 204, 204));
        lblReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/ReturnItem.png"))); // NOI18N
        lblReturn.setText("Return Item");
        lblReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReturn.setOpaque(true);
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblReturnMousePressed(evt);
            }
        });
        jXPanel4.add(lblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 200, 100));

        lblCus.setBackground(new java.awt.Color(204, 204, 204));
        lblCus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/ManageCus.png"))); // NOI18N
        lblCus.setText("Manage Customer");
        lblCus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCus.setOpaque(true);
        lblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCusMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCusMouseClicked(evt);
            }
        });
        jXPanel4.add(lblCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 100));

        lblItem.setBackground(new java.awt.Color(204, 204, 204));
        lblItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Item.png"))); // NOI18N
        lblItem.setText("Manage Item");
        lblItem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblItem.setOpaque(true);
        lblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblItemMousePressed(evt);
            }
        });
        jXPanel4.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 100));

        lblSup.setBackground(new java.awt.Color(204, 204, 204));
        lblSup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/ManageSup.png"))); // NOI18N
        lblSup.setText("Manage Supplier");
        lblSup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSup.setOpaque(true);
        lblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSupMousePressed(evt);
            }
        });
        jXPanel4.add(lblSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 100));

        jXLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/h1.jpg"))); // NOI18N
        jXPanel4.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 670));

        jXPanel2.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 660));

        jXPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Settings.png"))); // NOI18N
        jXLabel4.setText("Settigs");
        jXLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jXLabel4MousePressed(evt);
            }
        });
        jXPanel5.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 150));

        lblSupOrder.setBackground(new java.awt.Color(204, 204, 204));
        lblSupOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblSupOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Supplier Order.png"))); // NOI18N
        lblSupOrder.setText("Supplier Order");
        lblSupOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSupOrder.setOpaque(true);
        lblSupOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupOrderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSupOrderMousePressed(evt);
            }
        });
        jXPanel5.add(lblSupOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 100));

        lblCusOrder.setBackground(new java.awt.Color(204, 204, 204));
        lblCusOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblCusOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/CustomerOrder.png"))); // NOI18N
        lblCusOrder.setText("Customer Order");
        lblCusOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCusOrder.setOpaque(true);
        lblCusOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCusOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCusOrderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCusOrderMousePressed(evt);
            }
        });
        jXPanel5.add(lblCusOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 100));

        lblView.setBackground(new java.awt.Color(204, 204, 204));
        lblView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/View Reports.png"))); // NOI18N
        lblView.setText("View Reports");
        lblView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblView.setOpaque(true);
        lblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewMousePressed(evt);
            }
        });
        jXPanel5.add(lblView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 200, 100));

        jXLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/h1.jpg"))); // NOI18N
        jXPanel5.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 580));

        jXPanel2.add(jXPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, 220, 600));

        jXPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jXPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrDetail.setBackground(new java.awt.Color(102, 102, 102));
        lblOrDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblOrDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Orders.png"))); // NOI18N
        lblOrDetail.setText("Order Details");
        lblOrDetail.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblOrDetail.setOpaque(true);
        lblOrDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrDetailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOrDetailMousePressed(evt);
            }
        });
        jXPanel6.add(lblOrDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 200, 60));

        lblEmployee.setBackground(new java.awt.Color(102, 102, 102));
        lblEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/ManageSup.png"))); // NOI18N
        lblEmployee.setText("Employees");
        lblEmployee.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblEmployee.setOpaque(true);
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEmployeeMousePressed(evt);
            }
        });
        jXPanel6.add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 200, 60));

        lblUser.setBackground(new java.awt.Color(102, 102, 102));
        lblUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/ManageSup.png"))); // NOI18N
        lblUser.setText("Manage Users");
        lblUser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblUser.setOpaque(true);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUserMousePressed(evt);
            }
        });
        jXPanel6.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 200, 60));

        jXPanel2.add(jXPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, 910, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/h4.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlHmeLayout = new javax.swing.GroupLayout(pnlHme);
        pnlHme.setLayout(pnlHmeLayout);
        pnlHmeLayout.setHorizontalGroup(
            pnlHmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1058, 1058, 1058))
        );
        pnlHmeLayout.setVerticalGroup(
            pnlHmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jXPanel2.add(pnlHme, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 900, 460));

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addComponent(jXPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(220, 220, 220))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMousePressed
        CustomerManage i1 = new CustomerManage();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblCusMousePressed

    private void lblSupOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrderMousePressed
        SupplierOrder s1 = new SupplierOrder(userId);
        s1.setVisible(true);
    }//GEN-LAST:event_lblSupOrderMousePressed

    private void lblItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMousePressed
        ManageItem i1 = new ManageItem(null);
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblItemMousePressed

    private void lblSupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMousePressed
        ManageSupplier i1 = new ManageSupplier();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblSupMousePressed

    private void lblReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMousePressed
        ReturnItem i1 = new ReturnItem();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblReturnMousePressed

    private void lblCusOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrderMousePressed
        CustomerOrders i1 = new CustomerOrders(userId);
        i1.setVisible(true);
    }//GEN-LAST:event_lblCusOrderMousePressed

    private void lblUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMousePressed

        ManageUser i1 = new ManageUser();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblUserMousePressed

    private void lblEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMousePressed
        Employees i1 = new Employees();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblEmployeeMousePressed

    private void lblOrDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrDetailMousePressed
        Orders i1 = new Orders();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblOrDetailMousePressed

    private void lblViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMousePressed
        PnlView i1 = new PnlView();
        pnlHme.removeAll();
        pnlHme.add(i1);
        i1.setVisible(true);
    }//GEN-LAST:event_lblViewMousePressed

    private void lblCusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseEntered
        lblCus.setBackground(Color.BLUE);
        //lblCus.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCusMouseEntered

    private void lblSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMouseEntered
        lblSup.setBackground(Color.BLUE);
        //lblSup.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblSupMouseEntered

    private void lblItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseEntered
        lblItem.setBackground(Color.BLUE);
        //lblItem.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblItemMouseEntered

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        lblUser.setBackground(Color.RED);
        //lblUser.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblOrDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrDetailMouseEntered
        lblOrDetail.setBackground(Color.RED);
        // lblOrDetail.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblOrDetailMouseEntered

    private void lblEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseEntered
        lblEmployee.setBackground(Color.RED);
        //lblEmployee.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblEmployeeMouseEntered

    private void lblViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseEntered
        lblView.setBackground(Color.BLUE);
        //lblView.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblViewMouseEntered

    private void lblReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseEntered
        lblReturn.setBackground(Color.BLUE);
        // lblReturn.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblReturnMouseEntered

    private void lblCusOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrderMouseEntered
        lblCusOrder.setBackground(Color.BLUE);
        // lblCusOrder.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCusOrderMouseEntered

    private void lblSupOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrderMouseEntered
        lblSupOrder.setBackground(Color.BLUE);
        //lblSupOrder.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblSupOrderMouseEntered

    private void lblCusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseExited
        lblCus.setBackground(new Color(204, 204, 204));
        lblCus.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCusMouseExited

    private void lblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusMouseClicked

    }//GEN-LAST:event_lblCusMouseClicked

    private void lblSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupMouseExited
        lblSup.setBackground(new Color(204, 204, 204));
        lblSup.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSupMouseExited

    private void lblItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseExited
        lblItem.setBackground(new Color(204, 204, 204));
        lblItem.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblItemMouseExited

    private void lblViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseExited
        lblView.setBackground(new Color(204, 204, 204));
        lblView.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblViewMouseExited

    private void lblReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseExited
        lblReturn.setBackground(new Color(204, 204, 204));
        lblReturn.setForeground(Color.BLACK);
        // TODO add your handling code here:

    }//GEN-LAST:event_lblReturnMouseExited

    private void lblCusOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrderMouseExited
        lblCusOrder.setBackground(new Color(204, 204, 204));
        lblCusOrder.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCusOrderMouseExited

    private void lblSupOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrderMouseExited
        lblSupOrder.setBackground(new Color(204, 204, 204));
        lblSupOrder.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSupOrderMouseExited

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setBackground(new Color(102, 102, 102));
        lblUser.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblUserMouseExited

    private void lblOrDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrDetailMouseExited
        lblOrDetail.setBackground(new Color(102, 102, 102));
        lblOrDetail.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblOrDetailMouseExited

    private void lblEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseExited
        lblEmployee.setBackground(new Color(102, 102, 102));
        lblEmployee.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblEmployeeMouseExited

    private void jXLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel1MousePressed
        this.dispose();
    }//GEN-LAST:event_jXLabel1MousePressed

    private void jXLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel4MousePressed

        PasswordChange pr = new PasswordChange(pnlHme);
        pnlHme.removeAll();
        pnlHme.add(pr);
        pr.setVisible(true);
    }//GEN-LAST:event_jXLabel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXPanel jXPanel5;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private org.jdesktop.swingx.JXLabel lblCus;
    private org.jdesktop.swingx.JXLabel lblCusOrder;
    private org.jdesktop.swingx.JXLabel lblDate;
    private org.jdesktop.swingx.JXLabel lblEmployee;
    private org.jdesktop.swingx.JXLabel lblItem;
    private org.jdesktop.swingx.JXLabel lblOrDetail;
    private org.jdesktop.swingx.JXLabel lblReturn;
    private org.jdesktop.swingx.JXLabel lblSup;
    private org.jdesktop.swingx.JXLabel lblSupOrder;
    private org.jdesktop.swingx.JXLabel lblTime;
    private org.jdesktop.swingx.JXLabel lblUser;
    private org.jdesktop.swingx.JXLabel lblView;
    public org.jdesktop.swingx.JXPanel pnlHme;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String date = df.format(d1);
        lblDate.setText(date);
    }

    private void setTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date d1 = new Date();
                    String time = new SimpleDateFormat("hh:mm:ss aa").format(d1);
                    lblTime.setText(time);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();

    }

    public void visibility() {
        if (userId.equals("U003")) {
            lblUser.setVisible(true);
            lblOrDetail.setVisible(true);
            lblEmployee.setVisible(true);
        }else{
            lblUser.setVisible(false);
            lblOrDetail.setVisible(false);
            lblEmployee.setVisible(false);
        }
    }

}
