/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.phoneshop.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.phoneshop.controller.ManageSupplierController;
import lk.ijse.phoneshop.core.dto.CustomerDTO;
import lk.ijse.phoneshop.core.dto.SupplierDTO;

/**
 *
 * @author HP
 */
public class ManageSupplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageSupplier
     */
    public ManageSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtSNic = new org.jdesktop.swingx.JXTextField();
        txtMobile = new org.jdesktop.swingx.JXTextField();
        txtComNo = new org.jdesktop.swingx.JXTextField();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtCompany = new org.jdesktop.swingx.JXTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        txtEmail = new org.jdesktop.swingx.JXTextField();
        txtsName = new org.jdesktop.swingx.JXTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnChange1 = new javax.swing.JButton();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        btnSearch1 = new javax.swing.JButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel2.setText("Manage Supplier");
        jXLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 450, 70));

        jXLabel3.setText("Supplier NIC");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        jXLabel4.setText("Supplier Mobile No.");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        jXLabel5.setText("e-mail Address");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 110, 40));

        txtSNic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNicActionPerformed(evt);
            }
        });
        jXPanel1.add(txtSNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, 30));

        txtMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        jXPanel1.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, 30));

        txtComNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComNoActionPerformed(evt);
            }
        });
        jXPanel1.add(txtComNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 30));

        jXLabel6.setText("T.P. No. (Company)");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 30));

        txtCompany.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });
        jXPanel1.add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 340, 30));

        jXLabel7.setText("Company Name");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, 40));

        jXLabel8.setText("Supplier Name");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 100, 40));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jXPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 340, 30));

        txtsName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsNameActionPerformed(evt);
            }
        });
        jXPanel1.add(txtsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 340, 30));

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Search1.png"))); // NOI18N
        btnSearch.setText("Find");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jXPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 150, 40));

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Create New.png"))); // NOI18N
        btnAdd.setText("Create New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jXPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 190, 40));

        btnRemove.setBackground(new java.awt.Color(153, 153, 153));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Remove.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jXPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, 40));

        btnView.setBackground(new java.awt.Color(153, 153, 153));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/View Reports.png"))); // NOI18N
        btnView.setText("View All");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jXPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 160, 40));

        btnChange1.setBackground(new java.awt.Color(153, 153, 153));
        btnChange1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChange1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Change1.png"))); // NOI18N
        btnChange1.setText("Change");
        btnChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange1ActionPerformed(evt);
            }
        });
        jXPanel1.add(btnChange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, 40));

        jXLabel10.setText("(xxx-xxxxxxx)");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 20));

        jXLabel9.setText("(xxx-xxxxxxx)");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, 20));

        btnSearch1.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Clr.png"))); // NOI18N
        btnSearch1.setText("Refresh");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jXPanel1.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, 40));

        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jXLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 870, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            SupplierDTO supplierDTO = new SupplierDTO(txtSNic.getText());
            SupplierDTO result = ManageSupplierController.searchSupplier(supplierDTO);
            if (result != null) {
                txtsName.setText(result.getsName());
                txtMobile.setText(result.getsMobile());
                txtEmail.setText(result.getsEmail());
                txtCompany.setText(result.getComName());
                txtComNo.setText(result.getComTele());
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are You Want to Add this Supplier ?");
        if (confirm == 0) {
            String comNo = txtComNo.getText();
            if (comNo.matches("[0-9]{3}[-][0-9]{7}")) {
                String email = txtEmail.getText();
                if (email.matches("[a-z]+@[a-z]+\\.[a-z]+") || email.matches("")) {
                    String mobile = txtMobile.getText();
                    if (mobile.matches("[0-9]{3}[-][0-9]{7}")) {
                        String nic = txtSNic.getText();
                        if (nic.matches("[0-9]{9}[Vv]")) {

                            try {
                                SupplierDTO supplierDTO = new SupplierDTO(txtSNic.getText(), txtsName.getText(), txtMobile.getText(), txtEmail.getText(), txtCompany.getText(), txtComNo.getText());
                                boolean isAdded = ManageSupplierController.addSupplier(supplierDTO);
                                if (isAdded) {
                                    JOptionPane.showMessageDialog(this, "Sucessfully Added");
                                } else {
                                    JOptionPane.showMessageDialog(this, "Added Failled");
                                }
                            } catch (Exception ex) {
                                Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid NIC");
                            txtSNic.selectAll();
                            txtSNic.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Insert Supplier Mobile NO. to Correct Format");
                        txtMobile.selectAll();
                        txtMobile.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Insert Correct email Address");
                    txtEmail.selectAll();
                    txtEmail.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insert Company TelePhone no. to Correct Format");
                txtComNo.selectAll();
                txtComNo.requestFocus();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are You Sure Delete from Supplier this System?");
        if (confirm == 0) {

            try {
                SupplierDTO supplierDTO = new SupplierDTO(txtSNic.getText());
                boolean isAdded = ManageSupplierController.deleteSupplier(supplierDTO);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Delete Successfully");
                    txtsName.setText("");
                    txtSNic.setText("");
                    txtMobile.setText("");
                    txtEmail.setText("");
                    txtCompany.setText("");
                    txtComNo.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Delete Failled");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsNameActionPerformed
        txtMobile.requestFocus();
    }//GEN-LAST:event_txtsNameActionPerformed

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        ViewSupplier s1 = new ViewSupplier();
        s1.setVisible(true);
    }//GEN-LAST:event_btnViewMouseClicked

    private void txtSNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNicActionPerformed
        txtsName.requestFocus();
    }//GEN-LAST:event_txtSNicActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtComNo.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtComNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComNoActionPerformed
        txtCompany.requestFocus();
    }//GEN-LAST:event_txtComNoActionPerformed

    private void btnChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are You sure Update?");
        if (confirm == 0) {
            String comNo = txtComNo.getText();
            if (comNo.matches("[0-9]{3}[-][0-9]{7}")) {
                String email = txtEmail.getText();
                if (email.matches("[a-z]+@[a-z]+\\.[a-z]+") || email.matches("")) {
                    String mobile = txtMobile.getText();
                    if (mobile.matches("[0-9]{3}[-][0-9]{7}")) {
                        try {
                            String nic = txtSNic.getText();

                            SupplierDTO supplierDTO = new SupplierDTO(txtSNic.getText(), txtsName.getText(), txtMobile.getText(), txtEmail.getText(), txtCompany.getText(), txtComNo.getText());
                            boolean isAdded = ManageSupplierController.updateSupplier(supplierDTO);
                            if (isAdded) {
                                JOptionPane.showMessageDialog(this, "Updated..");
                            } else {
                                JOptionPane.showMessageDialog(this, "Update Failled...");
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Insert Supplier Mobile NO. to Correct Format");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Insert Correct email Address");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Insert Company TelePhone no. to Correct Format");
            }
        }
    }//GEN-LAST:event_btnChange1ActionPerformed

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        txtsName.setText("");
        txtSNic.setText("");
        txtMobile.setText("");
        txtEmail.setText("");
        txtCompany.setText("");
        txtComNo.setText("");
    }//GEN-LAST:event_btnSearch1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange1;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnView;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXTextField txtComNo;
    private org.jdesktop.swingx.JXTextField txtCompany;
    private org.jdesktop.swingx.JXTextField txtEmail;
    private org.jdesktop.swingx.JXTextField txtMobile;
    private org.jdesktop.swingx.JXTextField txtSNic;
    private org.jdesktop.swingx.JXTextField txtsName;
    // End of variables declaration//GEN-END:variables
}
