/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.phoneshop.view;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class Orders extends javax.swing.JInternalFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrder = new org.jdesktop.swingx.JXPanel();
        lblSupOrDetail = new org.jdesktop.swingx.JXLabel();
        lblCusOrDetail = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();

        pnlOrder.setBackground(new java.awt.Color(255, 255, 255));
        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSupOrDetail.setBackground(new java.awt.Color(204, 204, 204));
        lblSupOrDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblSupOrDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/Supplier Order.png"))); // NOI18N
        lblSupOrDetail.setText("Supplier Order Detail");
        lblSupOrDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupOrDetail.setOpaque(true);
        lblSupOrDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupOrDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupOrDetailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSupOrDetailMousePressed(evt);
            }
        });
        pnlOrder.add(lblSupOrDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 100));

        lblCusOrDetail.setBackground(new java.awt.Color(204, 204, 204));
        lblCusOrDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblCusOrDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/CustomerOrder.png"))); // NOI18N
        lblCusOrDetail.setText("Customer Order Detail");
        lblCusOrDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCusOrDetail.setOpaque(true);
        lblCusOrDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCusOrDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCusOrDetailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCusOrDetailMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCusOrDetailMouseClicked(evt);
            }
        });
        pnlOrder.add(lblCusOrDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 100));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/order.jpg"))); // NOI18N
        pnlOrder.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        jXLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/phoneshop/image/o1.jpg"))); // NOI18N
        pnlOrder.add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 650, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCusOrDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrDetailMousePressed
          CustomerOrderDetails c1=new CustomerOrderDetails();
          c1.setVisible(true);
    }//GEN-LAST:event_lblCusOrDetailMousePressed

    private void lblCusOrDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrDetailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCusOrDetailMouseClicked

    private void lblSupOrDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrDetailMousePressed
       SupOrderDetail s1=new SupOrderDetail();
       s1.setVisible(true);
       
    }//GEN-LAST:event_lblSupOrDetailMousePressed

    private void lblCusOrDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrDetailMouseEntered
        lblCusOrDetail.setBackground(Color.YELLOW);
    }//GEN-LAST:event_lblCusOrDetailMouseEntered

    private void lblSupOrDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrDetailMouseEntered
       lblSupOrDetail.setBackground(Color.YELLOW);
    }//GEN-LAST:event_lblSupOrDetailMouseEntered

    private void lblCusOrDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusOrDetailMouseExited
       lblCusOrDetail.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblCusOrDetailMouseExited

    private void lblSupOrDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupOrDetailMouseExited
       lblSupOrDetail.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_lblSupOrDetailMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel lblCusOrDetail;
    private org.jdesktop.swingx.JXLabel lblSupOrDetail;
    private org.jdesktop.swingx.JXPanel pnlOrder;
    // End of variables declaration//GEN-END:variables
}
